# Generated by Django 5.2.8 on 2026-02-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoSource',
            fields=[
                ('geo_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('region_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('city_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('network_isp_name', models.CharField(blank=True, max_length=200, null=True)),
                ('network_type', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': '[location].[geo_source]',
                'managed': False,
            },
        ),
    ]
