from django.urls import path

from . import views, views_api

app_name = 'quizadmin'

urlpatterns = [
    path('',              views.dashboard_page,           name='dashboard'),
    path('review/',       views.review_queue_page,        name='review_queue'),
    path('books/',        views.books_page,               name='books'),
    path('generation-jobs/', views.generation_jobs_page,   name='generation_jobs'),
    path('questions/',    views.question_bank_page,       name='question_bank'),
    path('question/create/',           views.question_create_page,    name='question_create'),
    path('question/<int:question_id>/edit/', views.question_edit_page, name='question_edit'),
    path('question/<int:question_id>/analytics/', views.question_analytics_page, name='question_analytics'),
    path('question/<int:question_id>/history/',   views.question_history_page,   name='question_history'),
    path('quiz/',                          views.quiz_list_page,         name='quiz_list'),
    path('quiz/create/',                   views.quiz_create_page,       name='quiz_create'),
    path('quiz/<int:exam_id>/edit/',       views.quiz_edit_page,         name='quiz_edit'),
    path('quiz/<int:exam_id>/leaderboard/',views.quiz_leaderboard_page,  name='quiz_leaderboard'),
    path('quiz/<int:exam_id>/preview/',    views.quiz_preview_page,      name='quiz_preview'),
    path('quiz/<int:exam_id>/print/',      views.quiz_print_page,        name='quiz_print'),
    path('quiz/<int:exam_id>/workflow/',   views.quiz_workflow_log_page, name='quiz_workflow_log'),
    path('creators/',                      views.quiz_creators_page,     name='quiz_creators'),
    path('quiz/<int:exam_id>/take/', views.quiz_take_page, name='quiz_take_page'),
    path('quiz/<int:exam_id>/certificate-template/', views.quiz_certificate_template_page, name='quiz_certificate_template'),
    path('api/quiz/<int:exam_id>/certificate-template/', views_api.api_quiz_certificate_template_save, name='api_quiz_certificate_template_save'),
    path('analytics/',                     views.analytics_dashboard_page,            name='analytics_dashboard'),
    path('webhooks/',                      views.webhooks_page,                       name='webhooks_page'),
    path('flagged/',                       views.flagged_questions_page,              name='flagged_questions_page'),
    path('help/',                          views.help_page,                           name='help_page'),
    path('proctoring/',                    views.proctoring_dashboard_page,           name='proctoring_dashboard'),
    path('proctoring/feed/',               views.proctoring_dashboard_feed_partial,   name='proctoring_dashboard_feed'),
    path('proctoring/session/<int:session_id>/', views.proctoring_session_audit_page, name='proctoring_session_audit'),

    path('api/approve/',  views_api.api_coll_question_approve,   name='api_coll_question_approve'),
    path('api/reject/',   views_api.api_coll_question_reject,    name='api_coll_question_reject'),
    path('api/skip/',     views_api.api_coll_question_skip,      name='api_coll_question_skip'),
    path('api/question/create/',                   views_api.api_coll_question_create,   name='api_coll_question_create'),
    path('api/question/<int:question_id>/update/', views_api.api_coll_question_update,   name='api_coll_question_update'),
    path('api/question/<int:question_id>/delete/', views_api.api_coll_question_delete,   name='api_coll_question_delete'),
    path('api/question/bulk-status/',              views_api.api_coll_question_bulk_status, name='api_coll_question_bulk_status'),
    path('api/question/export-csv/',               views_api.api_coll_question_export_csv,  name='api_coll_question_export_csv'),
    path('api/question/import-csv/',               views_api.api_coll_question_import_csv,  name='api_coll_question_import_csv'),
    path('api/quiz/create/',               views_api.api_coll_exam_create,  name='api_coll_exam_create'),
    path('api/quiz/<int:exam_id>/update/', views_api.api_coll_exam_update,  name='api_coll_exam_update'),
    path('api/quiz/<int:exam_id>/clone/',  views_api.api_coll_exam_clone,   name='api_coll_exam_clone'),
    path('api/quiz/<int:exam_id>/delete/', views_api.api_coll_exam_delete,  name='api_coll_exam_delete'),
    path('api/creator/grant/',                          views_api.api_quiz_creator_grant,          name='api_quiz_creator_grant'),
    path('api/creator/<int:permission_id>/revoke/',     views_api.api_quiz_creator_revoke,         name='api_quiz_creator_revoke'),
    path('api/creator/<int:permission_id>/update-expiry/', views_api.api_quiz_creator_update_expiry, name='api_quiz_creator_update_expiry'),
    path('api/creator/search-users/',                   views_api.api_quiz_creator_search_users,   name='api_quiz_creator_search_users'),
    path('api/proctoring/violation/<int:violation_id>/forgive/', views_api.api_proctoring_forgive_violation, name='api_proctoring_forgive_violation'),
]
