-- Auto-generated from content/content_type_registry.py
-- DO NOT EDIT BY HAND — regenerate via the helper command.
-- 
-- This script stamps SQL Server extended properties on every column
-- registered in CONTENT_TYPE_REGISTRY so you can inspect the role from
-- the database side (SSMS column tooltip, sys.extended_properties query).
-- 
-- Idempotent: drops + re-adds the property on each run. Safe to re-run
-- after any registry change.

SET XACT_ABORT ON;
BEGIN TRY
    BEGIN TRANSACTION;

    -- ==== art -> [blog_art].[coll_artwork] ====
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_art' AND t.name = N'coll_artwork' AND c.name = N'blog_art_coll_artwork_id' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'blog_art_coll_artwork_id';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'art:pk_field', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'blog_art_coll_artwork_id';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_art' AND t.name = N'coll_artwork' AND c.name = N'artwork_title_bn' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'artwork_title_bn';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'art:title_bn_field', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'artwork_title_bn';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_art' AND t.name = N'coll_artwork' AND c.name = N'artwork_title_en' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'artwork_title_en';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'art:title_en_field', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'artwork_title_en';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_art' AND t.name = N'coll_artwork' AND c.name = N'artwork_slug' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'artwork_slug';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'art:slug_field', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'artwork_slug';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_art' AND t.name = N'coll_artwork' AND c.name = N'artwork_summary_bn' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'artwork_summary_bn';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'art:summary_bn_field', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'artwork_summary_bn';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_art' AND t.name = N'coll_artwork' AND c.name = N'artwork_summary_en' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'artwork_summary_en';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'art:summary_en_field', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'artwork_summary_en';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_art' AND t.name = N'coll_artwork' AND c.name = N'is_published' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'is_published';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'art:is_published_field', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'is_published';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_art' AND t.name = N'coll_artwork' AND c.name = N'is_active' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'is_active';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'art:is_active_field', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'is_active';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_art' AND t.name = N'coll_artwork' AND c.name = N'is_featured' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'is_featured';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'art:is_featured_field', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'is_featured';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_art' AND t.name = N'coll_artwork' AND c.name = N'bookmark_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'bookmark_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'art:bookmark_count_field', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'bookmark_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_art' AND t.name = N'coll_artwork' AND c.name = N'like_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'like_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'art:like_count_field', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'like_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_art' AND t.name = N'coll_artwork' AND c.name = N'view_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'view_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'art:view_count_field', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'view_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_art' AND t.name = N'coll_artwork' AND c.name = N'comment_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'comment_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'art:comment_count_field', @level0type = N'SCHEMA', @level0name = N'blog_art', @level1type = N'TABLE', @level1name = N'coll_artwork', @level2type = N'COLUMN', @level2name = N'comment_count';

    -- ==== story -> [blog_stories].[coll_story] ====
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_stories' AND t.name = N'coll_story' AND c.name = N'blog_stories_coll_story_id' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'blog_stories_coll_story_id';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'story:pk_field', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'blog_stories_coll_story_id';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_stories' AND t.name = N'coll_story' AND c.name = N'story_title_bn' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'story_title_bn';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'story:title_bn_field', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'story_title_bn';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_stories' AND t.name = N'coll_story' AND c.name = N'story_title_en' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'story_title_en';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'story:title_en_field', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'story_title_en';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_stories' AND t.name = N'coll_story' AND c.name = N'story_slug' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'story_slug';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'story:slug_field', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'story_slug';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_stories' AND t.name = N'coll_story' AND c.name = N'story_summary_bn' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'story_summary_bn';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'story:summary_bn_field', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'story_summary_bn';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_stories' AND t.name = N'coll_story' AND c.name = N'is_published' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'is_published';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'story:is_published_field', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'is_published';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_stories' AND t.name = N'coll_story' AND c.name = N'is_active' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'is_active';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'story:is_active_field', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'is_active';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_stories' AND t.name = N'coll_story' AND c.name = N'is_featured' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'is_featured';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'story:is_featured_field', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'is_featured';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_stories' AND t.name = N'coll_story' AND c.name = N'bookmark_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'bookmark_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'story:bookmark_count_field', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'bookmark_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_stories' AND t.name = N'coll_story' AND c.name = N'like_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'like_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'story:like_count_field', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'like_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_stories' AND t.name = N'coll_story' AND c.name = N'view_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'view_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'story:view_count_field', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'view_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_stories' AND t.name = N'coll_story' AND c.name = N'comment_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'comment_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'story:comment_count_field', @level0type = N'SCHEMA', @level0name = N'blog_stories', @level1type = N'TABLE', @level1name = N'coll_story', @level2type = N'COLUMN', @level2name = N'comment_count';

    -- ==== poem -> [blog_poem].[coll_poem_entry] ====
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'blog_poem_coll_poem_entry_id' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'blog_poem_coll_poem_entry_id';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:pk_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'blog_poem_coll_poem_entry_id';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'poem_title_bn' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'poem_title_bn';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:title_bn_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'poem_title_bn';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'poem_title_en' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'poem_title_en';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:title_en_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'poem_title_en';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'poem_slug' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'poem_slug';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:slug_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'poem_slug';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'poem_summary_bn' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'poem_summary_bn';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:summary_bn_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'poem_summary_bn';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'poem_summary_en' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'poem_summary_en';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:summary_en_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'poem_summary_en';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'is_published' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'is_published';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:is_published_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'is_published';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'is_active' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'is_active';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:is_active_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'is_active';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'is_featured' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'is_featured';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:is_featured_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'is_featured';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'poem_status_code' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'poem_status_code';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:status_code_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'poem_status_code';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'bookmark_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'bookmark_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:bookmark_count_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'bookmark_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'like_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'like_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:like_count_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'like_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'view_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'view_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:view_count_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'view_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_poem' AND t.name = N'coll_poem_entry' AND c.name = N'comment_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'comment_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'poem:comment_count_field', @level0type = N'SCHEMA', @level0name = N'blog_poem', @level1type = N'TABLE', @level1name = N'coll_poem_entry', @level2type = N'COLUMN', @level2name = N'comment_count';

    -- ==== destination -> [blog_bangladesh].[coll_destination] ====
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'blog_bangladesh_coll_destination_id' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'blog_bangladesh_coll_destination_id';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:pk_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'blog_bangladesh_coll_destination_id';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'destination_name_bn' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'destination_name_bn';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:title_bn_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'destination_name_bn';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'destination_name_en' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'destination_name_en';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:title_en_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'destination_name_en';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'destination_slug' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'destination_slug';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:slug_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'destination_slug';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'destination_short_description_bn' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'destination_short_description_bn';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:summary_bn_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'destination_short_description_bn';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'destination_short_description_en' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'destination_short_description_en';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:summary_en_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'destination_short_description_en';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'is_published' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'is_published';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:is_published_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'is_published';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'is_active' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'is_active';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:is_active_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'is_active';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'is_featured' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'is_featured';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:is_featured_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'is_featured';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'destination_status' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'destination_status';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:status_code_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'destination_status';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'bookmark_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'bookmark_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:bookmark_count_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'bookmark_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'like_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'like_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:like_count_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'like_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'view_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'view_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:view_count_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'view_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_destination' AND c.name = N'comment_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'comment_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'destination:comment_count_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_destination', @level2type = N'COLUMN', @level2name = N'comment_count';

    -- ==== media -> [blog_bangladesh].[coll_media_entry] ====
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_media_entry' AND c.name = N'blog_bangladesh_coll_media_entry_id' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'blog_bangladesh_coll_media_entry_id';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'media:pk_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'blog_bangladesh_coll_media_entry_id';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_media_entry' AND c.name = N'media_title_bn' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'media_title_bn';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'media:title_bn_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'media_title_bn';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_media_entry' AND c.name = N'media_title_en' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'media_title_en';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'media:title_en_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'media_title_en';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_media_entry' AND c.name = N'media_slug' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'media_slug';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'media:slug_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'media_slug';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_media_entry' AND c.name = N'is_published' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'is_published';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'media:is_published_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'is_published';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_media_entry' AND c.name = N'is_active' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'is_active';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'media:is_active_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'is_active';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_media_entry' AND c.name = N'is_featured' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'is_featured';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'media:is_featured_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'is_featured';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_media_entry' AND c.name = N'media_status' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'media_status';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'media:status_code_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'media_status';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_media_entry' AND c.name = N'bookmark_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'bookmark_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'media:bookmark_count_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'bookmark_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_media_entry' AND c.name = N'like_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'like_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'media:like_count_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'like_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_media_entry' AND c.name = N'view_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'view_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'media:view_count_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'view_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_bangladesh' AND t.name = N'coll_media_entry' AND c.name = N'comment_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'comment_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'media:comment_count_field', @level0type = N'SCHEMA', @level0name = N'blog_bangladesh', @level1type = N'TABLE', @level1name = N'coll_media_entry', @level2type = N'COLUMN', @level2name = N'comment_count';

    -- ==== debate -> [blog_debate].[coll_topic] ====
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_debate' AND t.name = N'coll_topic' AND c.name = N'blog_debate_coll_topic_id' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'blog_debate_coll_topic_id';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'debate:pk_field', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'blog_debate_coll_topic_id';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_debate' AND t.name = N'coll_topic' AND c.name = N'topic_title' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'topic_title';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'debate:title_bn_field', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'topic_title';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_debate' AND t.name = N'coll_topic' AND c.name = N'topic_description' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'topic_description';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'debate:summary_bn_field', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'topic_description';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_debate' AND t.name = N'coll_topic' AND c.name = N'is_active' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'is_active';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'debate:is_active_field', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'is_active';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_debate' AND t.name = N'coll_topic' AND c.name = N'bookmark_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'bookmark_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'debate:bookmark_count_field', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'bookmark_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_debate' AND t.name = N'coll_topic' AND c.name = N'like_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'like_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'debate:like_count_field', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'like_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_debate' AND t.name = N'coll_topic' AND c.name = N'view_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'view_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'debate:view_count_field', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'view_count';
    IF EXISTS (SELECT 1 FROM sys.extended_properties ep JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id JOIN sys.tables t ON t.object_id = c.object_id JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = N'blog_debate' AND t.name = N'coll_topic' AND c.name = N'comment_count' AND ep.name = N'registry_role')
        EXEC sp_dropextendedproperty @name = N'registry_role', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'comment_count';
    EXEC sp_addextendedproperty @name = N'registry_role', @value = N'debate:comment_count_field', @level0type = N'SCHEMA', @level0name = N'blog_debate', @level1type = N'TABLE', @level1name = N'coll_topic', @level2type = N'COLUMN', @level2name = N'comment_count';

    COMMIT TRANSACTION;
    PRINT 'phase 3b content type registry extended properties: SUCCESS';
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    DECLARE @msg NVARCHAR(4000) = ERROR_MESSAGE();
    PRINT 'phase 3b content type registry extended properties: FAILED — ' + @msg;
    THROW;
END CATCH;
