# Generated by Django 5.2.8 on 2026-02-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_article_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': False},
        ),
    ]
