# Generated by Django 5.2.8 on 2026-02-08 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('user_device_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hash_device_fingerprint', models.CharField(blank=True, max_length=32, null=True)),
                ('app_instance_id', models.CharField(blank=True, max_length=64, null=True)),
                ('app_platform_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_category', models.CharField(blank=True, max_length=100, null=True)),
                ('last_ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('browser_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'db_table': '[account].[user_device]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hash_phone_id', models.BinaryField(blank=True, max_length='max', null=True)),
                ('botdetection_phone_sim_slot_no', models.IntegerField(blank=True, null=True)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempt_count', models.IntegerField(blank=True, null=True)),
                ('auth_provider', models.CharField(blank=True, max_length=20, null=True)),
                ('auth_subject_hash', models.BinaryField(blank=True, max_length='max', null=True)),
                ('auth_account_age_days', models.IntegerField(blank=True, null=True)),
                ('face_embedding_hash', models.BinaryField(blank=True, max_length='max', null=True)),
                ('face_verified_at', models.DateTimeField(blank=True, null=True)),
                ('liveness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('age_years', models.SmallIntegerField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('is_phone_verified', models.BooleanField(blank=True, null=True)),
                ('is_social_verified', models.BooleanField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': '[account].[user_profile]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('user_session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link_evaluation_id', models.IntegerField()),
                ('link_user_profile_id', models.BigIntegerField(blank=True, null=True)),
                ('link_user_device_id', models.BigIntegerField(blank=True, null=True)),
                ('link_geo_source_id', models.IntegerField(blank=True, null=True)),
                ('link_intent_type_id', models.IntegerField(blank=True, null=True)),
                ('link_respondent_type_id', models.IntegerField(blank=True, null=True)),
                ('interaction_medium_name', models.CharField(blank=True, max_length=100, null=True)),
                ('session_ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('is_vpn_suspected', models.BooleanField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions_answered', models.IntegerField(blank=True, null=True)),
                ('total_session_ms', models.IntegerField(blank=True, null=True)),
                ('avg_time_per_question_ms', models.IntegerField(blank=True, null=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_flags', models.CharField(blank=True, max_length=200, null=True)),
                ('is_blocked', models.BooleanField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('is_authenticated_session', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': '[account].[user_session]',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='JournalistUser',
        ),
        migrations.DeleteModel(
            name='ModeratorUser',
        ),
        migrations.DeleteModel(
            name='StaffUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be 7-15 digits and may start with +.', regex='^\\+?[0-9]{7,15}$')]),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
