# Generated by Django 5.2.8 on 2026-02-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_userdevice_userprofile_usersession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('link_entity_type_id', models.IntegerField()),
                ('link_entity_id', models.IntegerField()),
                ('link_contact_type_id', models.IntegerField()),
                ('link_address_id', models.IntegerField(blank=True, null=True)),
                ('contact_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact_label_en', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_label_bn', models.CharField(blank=True, max_length=200, null=True)),
                ('is_primary', models.BooleanField()),
                ('is_verified', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '[contact].[contact]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('contact_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_type_code', models.CharField(max_length=100)),
                ('contact_type_name_en', models.CharField(max_length=100)),
                ('contact_type_name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_type_validation_regex', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_icon_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '[contact].[contact_type]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('entity_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('entity_type_code', models.CharField(max_length=200)),
                ('entity_type_name_en', models.CharField(max_length=200)),
                ('entity_type_name_bn', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '[contact].[entity_type]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link_address_id', models.BigIntegerField(blank=True, null=True)),
                ('link_gender_id', models.IntegerField(blank=True, null=True)),
                ('link_religion_id', models.IntegerField(blank=True, null=True)),
                ('first_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nid_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hash_nid_card_number', models.BinaryField(blank=True, max_length='max', null=True)),
                ('primary_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_email_address', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': '[person].[person]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefGender',
            fields=[
                ('gender_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('gender_name_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
                'db_table': '[person].[ref_gender]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefReligion',
            fields=[
                ('religion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('religion_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('religion_name_bn', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Religion',
                'verbose_name_plural': 'Religions',
                'db_table': '[person].[ref_religion]',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
