# Generated by Django 5.2.8 on 2026-02-10 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_remove_user_first_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('link_person_id', models.BigIntegerField()),
                ('link_contact_type_id', models.IntegerField(default=1)),
                ('email_address', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '[contact].[email]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('link_person_id', models.BigIntegerField()),
                ('link_contact_type_id', models.IntegerField(default=1)),
                ('country_calling_code', models.CharField(default='+880', max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '[contact].[phone]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefContactType',
            fields=[
                ('contact_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_type_code', models.CharField(max_length=50)),
                ('contact_type_name_en', models.CharField(max_length=100)),
                ('contact_type_name_bn', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '[contact].[ref_contact_type]',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactType',
        ),
        migrations.DeleteModel(
            name='EntityType',
        ),
    ]
