# Generated by Django 5.2.8 on 2026-02-11 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_user_auth_method_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('person_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('link_person_id', models.BigIntegerField()),
                ('link_address_id', models.IntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Person Address',
                'verbose_name_plural': 'Person Addresses',
                'db_table': '[person].[person_address]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefUserAuthMethodType',
            fields=[
                ('user_auth_method_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_method_type', models.CharField(max_length=20)),
                ('auth_method_name_en', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Auth Method Type',
                'verbose_name_plural': 'Auth Method Types',
                'db_table': '[account].[ref_user_auth_method_type]',
                'managed': False,
            },
        ),
    ]
