# Generated by Django 5.2.8 on 2026-02-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_register_unmanaged_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='uniq_user_email_ci',
        ),
    ]
